services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: krakend
    ports:
      - "9001:8080"
    environment:
      - KRAKEND_TIMEOUT=500ms
      - ORDER_SERVICE_URL=http://order-service:60052
      - USER_SERVICE_URL=http://user-service:50052
      - INVENTORY_SERVICE_URL=http://inventory-service:30052
    volumes:
      - ./api-gateway/krakend.json.tpl:/etc/krakend/krakend.json.tpl
