apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: order-service
spec:
  type: ExternalName
  externalName: kafka-controller-headless.kafka.svc.cluster.local
  ports:
    - name: kafka-port
      port: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: order-service
spec:
  type: ExternalName
  externalName: schema-registry-headless.kafka.svc.cluster.local
  ports:
    - name: schema-registry-port
      port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: order-service
spec:
  type: ExternalName
  externalName: user-service.user-service.svc.cluster.local
  ports:
    - port: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: order-service
spec:
  type: ExternalName
  externalName: inventory-service.inventory-service.svc.cluster.local
  ports:
    - port: 30051