apiVersion: batch/v1
kind: Job
metadata:
  name: order-db-migration
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: migrate/migrate
          command: ["migrate"]
          args:
            [
              "-path=/migrations",
              "-database",
              "postgres://devuser:devpass@order-service-db:5556/order_service?sslmode=disable",
              "up",
            ]
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: order-migrations
      restartPolicy: Never
  backoffLimit: 4
