## Kraft mode
kraft:
  enabled: true

## Listeners configuration
listeners:
  client:
    protocol: PLAINTEXT
    name: PLAINTEXT
  controller:
    protocol: PLAINTEXT
    name: CONTROLLER

# Number of Kafka nodes
replicaCount: 3

# Resource configuration
resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

# Storage configuration
persistence:
  enabled: true
  size: 5Gi

# Zookeeper is disabled in KRaft mode
zookeeper:
  enabled: false

# Ensure hostNetwork is not enabled for Minikube
hostNetwork: false

# Enable metrics for monitoring
metrics:
  kafka:
    enabled: true
  jmx:
    enabled: true

# Additional environment variables
extraEnvVars:
  - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
    value: "3"
  - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
    value: "2"
  - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
    value: "true"
  - name: KAFKA_HEAP_OPTS
    value: "-Xmx512m -Xms256m"
