## Schema Registry Configuration
## Disable the built-in Kafka
kafka:
  enabled: false

## External Kafka Configuration
externalKafka:
  # Explicitly include the protocol in the broker address
  brokers:
    - "PLAINTEXT://kafka.kafka.svc.cluster.local:9092"
  listener:
    protocol: PLAINTEXT

## Direct Schema Registry Configuration
## Double-check these settings are properly being applied
schemaRegistryHeapOpts: "-Xmx512M -Xms512M"

## Custom configuration overrides
## These are crucial for fixing the connection issues
customConfiguration: |-
  kafkastore.bootstrap.servers=PLAINTEXT://kafka.kafka.svc.cluster.local:9092
  kafkastore.security.protocol=PLAINTEXT
  debug=true

## Increase health check timeouts
livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 6

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 6

## Resource settings
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

## Debugging settings
debug: true
