apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: default
spec:
  type: ExternalName
  externalName: schema-registry.schema-registry.svc.cluster.local
  ports:
    - name: schema-registry-port
      port: 8081
