services:
  postgres:
    image: postgres:15-alpine
    container_name: order_service_db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: order_service
    ports:
      - "5556:5556"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5556 -c 'shared_preload_libraries=pgcrypto'

volumes:
  postgres_data:
