apiVersion: v1
kind: Service
metadata:
  name: api-gateway-external
  namespace: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 9001
      targetPort: 8080
      nodePort: 30080
  type: NodePort
