apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 2
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: go-microservice-api-gateway:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/krakend"]
        args: ["run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080"]
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
        env:
        - name: KRAKEND_PORT
          value: "8080"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
