apiVersion: v1
kind: Service
metadata:
  name: api-gateway-external
  namespace: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 9001
      targetPort: 8080
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: api-gateway
spec:
  type: ExternalName
  externalName: user-service.user-service.svc.cluster.local
  ports:
    - port: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: api-gateway
spec:
  type: ExternalName
  externalName: order-service.order-service.svc.cluster.local
  ports:
    - port: 60052
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: api-gateway
spec:
  type: ExternalName
  externalName: inventory-service.inventory-service.svc.cluster.local
  ports:
    - port: 30052
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: api-gateway
spec:
  type: ExternalName
  externalName: notification-service.notification-service.svc.cluster.local
  ports:
    - port: 20052