apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 2
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: go-microservice-api-gateway:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        command: ["/entrypoint.sh"]
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
        env:
        - name: ORDER_SERVICE_URL
          value: "http://order-service.order-service.svc.cluster.local:60052"
        - name: USER_SERVICE_URL
          value: "http://user-service.user-service.svc.cluster.local:50052"
        - name: INVENTORY_SERVICE_URL
          value: "http://inventory-service.inventory-service.svc.cluster.local:30052"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service.notification-service.svc.cluster.local:20052"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /__health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /__health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15
