services:
  user_service_db:
    image: postgres:15-alpine
    container_name: user_service_db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: user_service
    ports:
      - "5555:5555"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5555

  user-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
      - "50052:50052"
    environment:
      - DB_HOST=user_service_db
      - DB_USER=devuser
      - DB_PASS=devpass
      - DB_PORT=5555
      - DB_NAME=user_service
      - DB_SCHEMA=public
      - DB_SSLMODE=disable
      - DB_DRIVER=postgres
      - REPO_TYPE=gorm
      - GRPC_PORT=50051
      - HTTP_PORT=50052
    depends_on:
      - user_service_db

volumes:
  postgres_data:
