apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "environment": "{{ .Values.global.environment }}",
      "database": {
        "host": "{{ .Values.config.db.host }}",
        "port": {{ .Values.config.db.port }},
        "name": "{{ .Values.config.db.name }}",
        "user": "{{ .Values.config.db.user }}",
        "schema": "{{ .Values.config.db.schema }}",
        "sslmode": "{{ .Values.config.db.sslmode }}",
        "driver": "{{ .Values.config.db.driver }}"
      },
      "service": {
        "repoType": "{{ .Values.config.service.repoType }}",
        "grpcPort": {{ .Values.config.service.grpcPort }},
        "httpPort": {{ .Values.config.service.httpPort }}
      }
    }
