{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.db.host }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    app: {{ include "user-service.fullname" . }}-db
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  type: ClusterIP
{{- end }}
