{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "user-service.fullname" . }}-db-migration
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ include "user-service.fullname" . }}-db-migration
    spec:
      serviceAccountName: {{ include "user-service.serviceAccountName" . }}
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo "Waiting for {{ .Values.config.db.host }} (port {{ .Values.config.db.port }})...";
              until nc -z {{ .Values.config.db.host }} {{ .Values.config.db.port }}; do
                echo "DB not ready; retrying in 5s...";
                sleep 5;
              done;
              echo "DB is up! Proceeding with migrations...";
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      containers:
        - name: migrate
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}"
          imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
          command: ["migrate"]
          args:
            [
              "-path=/migrations",
              "-database",
              "{{ .Values.config.db.driver }}://{{ .Values.config.db.user }}:{{ .Values.config.db.password }}@{{ .Values.config.db.host }}:{{ .Values.config.db.port }}/{{ .Values.config.db.name }}?sslmode={{ .Values.config.db.sslmode }}",
              "up",
            ]
          volumeMounts:
            - name: migrations
              mountPath: /migrations
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
      volumes:
        - name: migrations
          configMap:
            name: {{ include "user-service.fullname" . }}-migrations
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
