{{- if and .Values.serviceAccount.create .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "user-service.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "user-service.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "user-service.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
{{- end }}
