apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: go-microservice-inventory-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 30051
              name: grpc
            - containerPort: 30052
              name: http
          env:
            - name: DB_HOST
              value: "inventory-service-db"
            - name: DB_USER
              value: "devuser"
            - name: DB_PASS
              value: "devpass"
            - name: DB_PORT
              value: "5557"
            - name: DB_NAME
              value: "inventory_service"
            - name: DB_SCHEMA
              value: "public"
            - name: DB_SSLMODE
              value: "disable"
            - name: DB_DRIVER
              value: "postgres"
            - name: REPO_TYPE
              value: "gorm"
            - name: GRPC_PORT
              value: "30051"
            - name: HTTP_PORT
              value: "30052"
            - name: KAFKA_BROKERS
              value: "kafka:9092"
            - name: SCHEMA_REGISTRY_URL
              value: "http://schema-registry:8081"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - name: grpc
      port: 30051
      targetPort: grpc
    - name: http
      port: 30052
      targetPort: http
  type: ClusterIP
