services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory_service_db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: inventory_service
    ports:
      - "5557:5557"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5557 -c 'shared_preload_libraries=pgcrypto'

volumes:
  postgres_data:
